// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"
	models "ethereum-fetcher/internal/store/pg/models"

	mock "github.com/stretchr/testify/mock"

	network "ethereum-fetcher/internal/network"
)

// EthereumProvider is an autogenerated mock type for the EthereumProvider type
type EthereumProvider struct {
	mock.Mock
}

// GetTransactionByHash provides a mock function with given fields: task
func (_m *EthereumProvider) GetTransactionByHash(task network.TxTask) (*models.Transaction, error) {
	ret := _m.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionByHash")
	}

	var r0 *models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(network.TxTask) (*models.Transaction, error)); ok {
		return rf(task)
	}
	if rf, ok := ret.Get(0).(func(network.TxTask) *models.Transaction); ok {
		r0 = rf(task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(network.TxTask) error); ok {
		r1 = rf(task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ScheduleTask provides a mock function with given fields: muxCtx, txHash
func (_m *EthereumProvider) ScheduleTask(muxCtx context.Context, txHash string) (<-chan network.TxResult, error) {
	ret := _m.Called(muxCtx, txHash)

	if len(ret) == 0 {
		panic("no return value specified for ScheduleTask")
	}

	var r0 <-chan network.TxResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (<-chan network.TxResult, error)); ok {
		return rf(muxCtx, txHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) <-chan network.TxResult); ok {
		r0 = rf(muxCtx, txHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan network.TxResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(muxCtx, txHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEthereumProvider creates a new instance of EthereumProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEthereumProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *EthereumProvider {
	mock := &EthereumProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
