name: CI LimeAPI Pipeline

on:
  push:
    branches:
      - main

env:
  API_PORT: ${{ vars.API_PORT }}
  ETH_NODE_URL: ${{ secrets.ETH_NODE_URL }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  DB_CONNECTION_URL: ${{ secrets.DB_CONNECTION_URL }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/limeapi
  UNIQUE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Create Buildx Builder
        run: docker buildx create --use

      - name: Build Multi-Arch Docker Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            --no-cache -t $IMAGE_NAME:$UNIQUE_TAG --build-arg API_PORT=${{ env.API_PORT }} --push .

      - name: Upload code artifact
        uses: actions/upload-artifact@v4
        with:
          name: code-artifact
          path: ./

      - name: Clean up unused Docker images and containers
        run: |
          # keep the last 30 images
          IMAGES_TO_REMOVE=$(docker images --format '{{.ID}}' | tail -n +31)

          # stop and remove containers older than 24 hours that are using those images
          if [ -n "$IMAGES_TO_REMOVE" ]; then
            # find all containers using the images to remove
            CONTAINERS_TO_REMOVE=$(docker ps -a --filter "ancestor=$IMAGES_TO_REMOVE" -q)

            # check each container and remove if older than 24 hours
            for CONTAINER in $CONTAINERS_TO_REMOVE; do
              CREATED_AT=$(docker inspect -f '{{.Created}}' $CONTAINER)
              if [[ $(date -d "$CREATED_AT" +%s) -lt $(date -d '24 hours ago' +%s) ]]; then
                docker stop $CONTAINER || true
                docker rm $CONTAINER || true
              fi
            done
          fi

          # remove the images that are not among the last 30
          if [ -n "$IMAGES_TO_REMOVE" ]; then
            docker rmi $IMAGES_TO_REMOVE || true
          fi

          # remove dangling images
          dangling_images=$(docker images -f "dangling=true" -q)
          if [ -n "$dangling_images" ]; then
            docker rmi $dangling_images || true
          fi

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download code artifact
        uses: actions/download-artifact@v4
        with:
          name: code-artifact

      - name: Create Docker network
        run: docker network create my_network

      - name: Run PostgreSQL container
        run: |
          docker run --name postgres_db --network my_network -d \
          -e POSTGRES_USER=${{ env.POSTGRES_USER }} \
          -e POSTGRES_PASSWORD=${{ env.POSTGRES_PASSWORD }} \
          -e POSTGRES_DB=postgres \
          -p 5432:5432 \
          -v postgres_data:/var/lib/postgresql/data \
          --restart unless-stopped \
          postgres:16.4

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..30}; do
            if docker exec postgres_db pg_isready -U ${{ env.POSTGRES_USER }}; then
              echo "PostgreSQL is ready!"
              break
            fi
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done
          if [ $i -eq 30 ]; then
            echo "PostgreSQL did not become ready in time."
            exit 1
          fi

      - name: Run linter
        run: |
          set -e
          docker run --rm --platform linux/amd64 -v ${{ github.workspace }}:/app -w /app golangci/golangci-lint:v1.60.3 golangci-lint run --timeout 3m ./...

      - name: Run unit tests
        run: |
          set -e
          docker run --rm --network my_network -e DB_CONNECTION_URL=${{ env.DB_CONNECTION_URL }} -v ${{ github.workspace }}:/app -w /app golang:1.23.0 go test ./... -count=1 -v

      - name: Notify Developer
        if: success()
        run: |
          MESSAGE="✅Linting and tests completed successfully on commit ${{ github.sha }}!"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=$MESSAGE"

      - name: Notify Developer on Failure
        if: failure()
        run: |
          MESSAGE="❌Linting or tests failed on commit ${{ github.sha }}. Please check the logs."
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=$MESSAGE"

      - name: Clean up Docker containers and network
        if: always()
        run: |
          if [ "$(docker ps -aq -f name=postgres_db)" ]; then
            docker stop postgres_db
            docker rm postgres_db
          fi
          if [ "$(docker network ls -q -f name=my_network)" ]; then  # Check if the network exists before removing
            docker network rm my_network
          fi

  push:
    runs-on: ubuntu-latest
    needs: [ build, test ]
    steps:
      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Create Buildx Builder
        run: docker buildx create --use

      - name: Set Image Tags
        run: |
          IMAGE_SHA_TAG=$IMAGE_NAME:${{ github.sha }}
          IMAGE_LATEST_TAG=$IMAGE_NAME:latest
          echo "IMAGE_SHA_TAG=$IMAGE_SHA_TAG" >> $GITHUB_ENV
          echo "IMAGE_LATEST_TAG=$IMAGE_LATEST_TAG" >> $GITHUB_ENV

      - name: Debug Tag Variables
        run: |
          echo "IMAGE_NAME: $IMAGE_NAME"
          echo "IMAGE_SHA_TAG: $IMAGE_SHA_TAG"
          echo "IMAGE_LATEST_TAG: IMAGE_LATEST_TAG"

      - name: Push Multi-Arch Docker image with SHA and latest tags
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t $IMAGE_NAME:$UNIQUE_TAG \
            -t $IMAGE_SHA_TAG \
            -t $IMAGE_LATEST_TAG \
            --push .

      - name: Notify Developer
        if: success()
        run: |
          MESSAGE="✅Docker image pushed successfully to GitHub Container Registry (GHCR)!%0A"
          MESSAGE+="Image tags:%0A- SHA: ${{ github.sha }}%0A- Latest"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=$MESSAGE"
