name: Deploy LimeAPI

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.30.1'

      - name: Use kubeconfig from Secrets
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/limeapi-deployment limeapi=ghcr.io/${{ github.repository_owner }}/limeapi:latest
          kubectl rollout status deployment/limeapi-deployment

      - name: Notify Developer
        if: success()
        run: |
          MESSAGE="✅Docker image ghcr.io/${{ github.repository_owner }}/limeapi:latest deployed to k8s cluster!"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=$MESSAGE"
